// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
  enumDesc,
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file frontendapi/frontend.proto.
 */
export const file_frontendapi_frontend: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Chpmcm9udGVuZGFwaS9mcm9udGVuZC5wcm90bxILZnJvbnRlbmRhcGkiQQoKUGFnaW5hdGlvbhIzCg9sYXN0X2NyZWF0ZWRfYXQYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wInoKBENoYXQSCgoCaWQYASABKAkSEwoLZGVzY3JpcHRpb24YAiADKAkSIwoGZ2VuZGVyGAMgASgOMhMuZnJvbnRlbmRhcGkuR2VuZGVyEiwKC2Nlb19kZXRhaWxzGAQgAygLMhcuZnJvbnRlbmRhcGkuQ0VPRGV0YWlscyI+Cg9HZXRDaGF0c1JlcXVlc3QSKwoKcGFnaW5hdGlvbhgBIAEoCzIXLmZyb250ZW5kYXBpLlBhZ2luYXRpb24iYQoQR2V0Q2hhdHNSZXNwb25zZRIgCgVjaGF0cxgBIAMoCzIRLmZyb250ZW5kYXBpLkNoYXQSKwoKcGFnaW5hdGlvbhgCIAEoCzIXLmZyb250ZW5kYXBpLlBhZ2luYXRpb24iOgoKQ0VPRGV0YWlscxILCgNrZXkYASABKAkSDgoGYWR2aWNlGAIgASgJEg8KB3N1bW1hcnkYAyABKAkiegoLQ2hhdE1lc3NhZ2USCgoCaWQYASABKAkSDwoHbWVzc2FnZRgCIAEoCRIPCgdpc191c2VyGAMgASgIEg8KB2Nob2ljZXMYBCADKAkSLAoLY2VvX2RldGFpbHMYBSADKAsyFy5mcm9udGVuZGFwaS5DRU9EZXRhaWxzIhIKEFN0YXJ0Q2hhdFJlcXVlc3QiTwoRU3RhcnRDaGF0UmVzcG9uc2USDwoHY2hhdF9pZBgBIAEoCRIpCgdtZXNzYWdlGAIgASgLMhguZnJvbnRlbmRhcGkuQ2hhdE1lc3NhZ2UiKQoWR2V0Q2hhdE1lc3NhZ2VzUmVxdWVzdBIPCgdjaGF0X2lkGAEgASgJIkUKF0dldENoYXRNZXNzYWdlc1Jlc3BvbnNlEioKCG1lc3NhZ2VzGAEgAygLMhguZnJvbnRlbmRhcGkuQ2hhdE1lc3NhZ2UiNgoSU2VuZE1lc3NhZ2VSZXF1ZXN0Eg8KB2NoYXRfaWQYASABKAkSDwoHbWVzc2FnZRgCIAEoCSJBChNTZW5kTWVzc2FnZVJlc3BvbnNlEioKCG1lc3NhZ2VzGAEgAygLMhguZnJvbnRlbmRhcGkuQ2hhdE1lc3NhZ2UqVgoGR2VuZGVyEhYKEkdFTkRFUl9VTlNQRUNJRklFRBAAEg8KC0dFTkRFUl9NQUxFEAESEQoNR0VOREVSX0ZFTUFMRRACEhAKDEdFTkRFUl9PVEhFUhADMtYCCg9Gcm9udGVuZFNlcnZpY2USRwoIR2V0Q2hhdHMSHC5mcm9udGVuZGFwaS5HZXRDaGF0c1JlcXVlc3QaHS5mcm9udGVuZGFwaS5HZXRDaGF0c1Jlc3BvbnNlEkoKCVN0YXJ0Q2hhdBIdLmZyb250ZW5kYXBpLlN0YXJ0Q2hhdFJlcXVlc3QaHi5mcm9udGVuZGFwaS5TdGFydENoYXRSZXNwb25zZRJcCg9HZXRDaGF0TWVzc2FnZXMSIy5mcm9udGVuZGFwaS5HZXRDaGF0TWVzc2FnZXNSZXF1ZXN0GiQuZnJvbnRlbmRhcGkuR2V0Q2hhdE1lc3NhZ2VzUmVzcG9uc2USUAoLU2VuZE1lc3NhZ2USHy5mcm9udGVuZGFwaS5TZW5kTWVzc2FnZVJlcXVlc3QaIC5mcm9udGVuZGFwaS5TZW5kTWVzc2FnZVJlc3BvbnNlQjFaL2dpdGh1Yi5jb20vY3VyaW9zd2l0Y2gvYWljZW8vYXBpL2dvO2Zyb250ZW5kYXBpYgZwcm90bzM",
    [file_google_protobuf_timestamp],
  );

/**
 * A token returned to retrieve a subsequented page of items.
 *
 * @generated from message frontendapi.Pagination
 */
export type Pagination = Message<"frontendapi.Pagination"> & {
  /**
   * The creation time of the last item in the current page.
   *
   * @generated from field: google.protobuf.Timestamp last_created_at = 1;
   */
  lastCreatedAt?: Timestamp;
};

/**
 * Describes the message frontendapi.Pagination.
 * Use `create(PaginationSchema)` to create a new message.
 */
export const PaginationSchema: GenMessage<Pagination> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 0);

/**
 * Details about a single chat.
 *
 * @generated from message frontendapi.Chat
 */
export type Chat = Message<"frontendapi.Chat"> & {
  /**
   * The ID of the chat.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The description of the chat as a set of parts.
   *
   * @generated from field: repeated string description = 2;
   */
  description: string[];

  /**
   * The gender of the user initiaiting the chat.
   *
   * @generated from field: frontendapi.Gender gender = 3;
   */
  gender: Gender;

  /**
   * Details of CEOs to presented to the user in this chat.
   *
   * @generated from field: repeated frontendapi.CEODetails ceo_details = 4;
   */
  ceoDetails: CEODetails[];
};

/**
 * Describes the message frontendapi.Chat.
 * Use `create(ChatSchema)` to create a new message.
 */
export const ChatSchema: GenMessage<Chat> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 1);

/**
 * A request to get all chats.
 *
 * @generated from message frontendapi.GetChatsRequest
 */
export type GetChatsRequest = Message<"frontendapi.GetChatsRequest"> & {
  /**
   * The pagination token to get the next page of chats.
   *
   * @generated from field: frontendapi.Pagination pagination = 1;
   */
  pagination?: Pagination;
};

/**
 * Describes the message frontendapi.GetChatsRequest.
 * Use `create(GetChatsRequestSchema)` to create a new message.
 */
export const GetChatsRequestSchema: GenMessage<GetChatsRequest> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 2);

/**
 * A response to a request to get all chats.
 *
 * @generated from message frontendapi.GetChatsResponse
 */
export type GetChatsResponse = Message<"frontendapi.GetChatsResponse"> & {
  /**
   * The fetched chats.
   *
   * @generated from field: repeated frontendapi.Chat chats = 1;
   */
  chats: Chat[];

  /**
   * The pagination token for the next page of chats.
   *
   * @generated from field: frontendapi.Pagination pagination = 2;
   */
  pagination?: Pagination;
};

/**
 * Describes the message frontendapi.GetChatsResponse.
 * Use `create(GetChatsResponseSchema)` to create a new message.
 */
export const GetChatsResponseSchema: GenMessage<GetChatsResponse> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 3);

/**
 * Details of a CEO.
 *
 * @generated from message frontendapi.CEODetails
 */
export type CEODetails = Message<"frontendapi.CEODetails"> & {
  /**
   * The key for the CEO for programmatic usage.
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * The advice from the CEO.
   *
   * @generated from field: string advice = 2;
   */
  advice: string;

  /**
   * The excerpt summary for the advice.
   *
   * @generated from field: string summary = 3;
   */
  summary: string;
};

/**
 * Describes the message frontendapi.CEODetails.
 * Use `create(CEODetailsSchema)` to create a new message.
 */
export const CEODetailsSchema: GenMessage<CEODetails> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 4);

/**
 * Details about a message within a chat.
 *
 * @generated from message frontendapi.ChatMessage
 */
export type ChatMessage = Message<"frontendapi.ChatMessage"> & {
  /**
   * The ID of the message.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The text content of the message.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Whether the message is from the user. Otherwise, it is from the assistant.
   *
   * @generated from field: bool is_user = 3;
   */
  isUser: boolean;

  /**
   * Choices for the user to select from for the message.
   *
   * @generated from field: repeated string choices = 4;
   */
  choices: string[];

  /**
   * Details of CEOs to present to the user.
   *
   * @generated from field: repeated frontendapi.CEODetails ceo_details = 5;
   */
  ceoDetails: CEODetails[];
};

/**
 * Describes the message frontendapi.ChatMessage.
 * Use `create(ChatMessageSchema)` to create a new message.
 */
export const ChatMessageSchema: GenMessage<ChatMessage> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 5);

/**
 * A request to begin a chat session.
 *
 * @generated from message frontendapi.StartChatRequest
 */
export type StartChatRequest = Message<"frontendapi.StartChatRequest"> & {};

/**
 * Describes the message frontendapi.StartChatRequest.
 * Use `create(StartChatRequestSchema)` to create a new message.
 */
export const StartChatRequestSchema: GenMessage<StartChatRequest> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 6);

/**
 * A response to a request to begin a chat session.
 *
 * @generated from message frontendapi.StartChatResponse
 */
export type StartChatResponse = Message<"frontendapi.StartChatResponse"> & {
  /**
   * The ID of the new chat.
   *
   * @generated from field: string chat_id = 1;
   */
  chatId: string;

  /**
   * The initial message of the chat.
   *
   * @generated from field: frontendapi.ChatMessage message = 2;
   */
  message?: ChatMessage;
};

/**
 * Describes the message frontendapi.StartChatResponse.
 * Use `create(StartChatResponseSchema)` to create a new message.
 */
export const StartChatResponseSchema: GenMessage<StartChatResponse> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 7);

/**
 * A request to get messages in a chat.
 *
 * @generated from message frontendapi.GetChatMessagesRequest
 */
export type GetChatMessagesRequest =
  Message<"frontendapi.GetChatMessagesRequest"> & {
    /**
     * The ID of the chat to get messages for.
     *
     * @generated from field: string chat_id = 1;
     */
    chatId: string;
  };

/**
 * Describes the message frontendapi.GetChatMessagesRequest.
 * Use `create(GetChatMessagesRequestSchema)` to create a new message.
 */
export const GetChatMessagesRequestSchema: GenMessage<GetChatMessagesRequest> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 8);

/**
 * A response to a request to get messages in a chat.
 *
 * @generated from message frontendapi.GetChatMessagesResponse
 */
export type GetChatMessagesResponse =
  Message<"frontendapi.GetChatMessagesResponse"> & {
    /**
     * The messages in the chat.
     *
     * @generated from field: repeated frontendapi.ChatMessage messages = 1;
     */
    messages: ChatMessage[];
  };

/**
 * Describes the message frontendapi.GetChatMessagesResponse.
 * Use `create(GetChatMessagesResponseSchema)` to create a new message.
 */
export const GetChatMessagesResponseSchema: GenMessage<GetChatMessagesResponse> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 9);

/**
 * A request to send a message in a chat.
 *
 * @generated from message frontendapi.SendMessageRequest
 */
export type SendMessageRequest = Message<"frontendapi.SendMessageRequest"> & {
  /**
   * The ID of the chat to send the message in.
   *
   * @generated from field: string chat_id = 1;
   */
  chatId: string;

  /**
   * The message to send.
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message frontendapi.SendMessageRequest.
 * Use `create(SendMessageRequestSchema)` to create a new message.
 */
export const SendMessageRequestSchema: GenMessage<SendMessageRequest> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 10);

/**
 * A response to a request to send a message in a chat.
 *
 * @generated from message frontendapi.SendMessageResponse
 */
export type SendMessageResponse = Message<"frontendapi.SendMessageResponse"> & {
  /**
   * New messages in the chat. This will include the request message as well.
   *
   * @generated from field: repeated frontendapi.ChatMessage messages = 1;
   */
  messages: ChatMessage[];
};

/**
 * Describes the message frontendapi.SendMessageResponse.
 * Use `create(SendMessageResponseSchema)` to create a new message.
 */
export const SendMessageResponseSchema: GenMessage<SendMessageResponse> =
  /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 11);

/**
 * A user gender.
 *
 * @generated from enum frontendapi.Gender
 */
export enum Gender {
  /**
   * Gender has not been set.
   *
   * @generated from enum value: GENDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Male.
   *
   * @generated from enum value: GENDER_MALE = 1;
   */
  MALE = 1,

  /**
   * Female.
   *
   * @generated from enum value: GENDER_FEMALE = 2;
   */
  FEMALE = 2,

  /**
   * Other.
   *
   * @generated from enum value: GENDER_OTHER = 3;
   */
  OTHER = 3,
}

/**
 * Describes the enum frontendapi.Gender.
 */
export const GenderSchema: GenEnum<Gender> =
  /*@__PURE__*/
  enumDesc(file_frontendapi_frontend, 0);

/**
 * The service for the frontend.
 *
 * @generated from service frontendapi.FrontendService
 */
export const FrontendService: GenService<{
  /**
   * Gets all chats.
   *
   * @generated from rpc frontendapi.FrontendService.GetChats
   */
  getChats: {
    methodKind: "unary";
    input: typeof GetChatsRequestSchema;
    output: typeof GetChatsResponseSchema;
  };
  /**
   * Starts a chat session.
   *
   * @generated from rpc frontendapi.FrontendService.StartChat
   */
  startChat: {
    methodKind: "unary";
    input: typeof StartChatRequestSchema;
    output: typeof StartChatResponseSchema;
  };
  /**
   * Gets messages in a chat.
   *
   * @generated from rpc frontendapi.FrontendService.GetChatMessages
   */
  getChatMessages: {
    methodKind: "unary";
    input: typeof GetChatMessagesRequestSchema;
    output: typeof GetChatMessagesResponseSchema;
  };
  /**
   * Sends a message in a chat.
   *
   * @generated from rpc frontendapi.FrontendService.SendMessage
   */
  sendMessage: {
    methodKind: "unary";
    input: typeof SendMessageRequestSchema;
    output: typeof SendMessageResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_frontendapi_frontend, 0);
