// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */

import { FrontendService } from "./frontend_pb";

/**
 * Gets all chats.
 *
 * @generated from rpc frontendapi.FrontendService.GetChats
 */
export const getChats = FrontendService.method.getChats;

/**
 * Starts a chat session.
 *
 * @generated from rpc frontendapi.FrontendService.StartChat
 */
export const startChat = FrontendService.method.startChat;

/**
 * Gets messages in a chat.
 *
 * @generated from rpc frontendapi.FrontendService.GetChatMessages
 */
export const getChatMessages = FrontendService.method.getChatMessages;

/**
 * Sends a message in a chat.
 *
 * @generated from rpc frontendapi.FrontendService.SendMessage
 */
export const sendMessage = FrontendService.method.sendMessage;
