// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetChatMessagesRequest, GetChatMessagesResponse, GetChatsRequest, GetChatsResponse, SendMessageRequest, SendMessageResponse, StartChatRequest, StartChatResponse } from "./frontend_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The service for the frontend.
 *
 * @generated from service frontendapi.FrontendService
 */
export const FrontendService = {
  typeName: "frontendapi.FrontendService",
  methods: {
    /**
     * Gets all chats.
     *
     * @generated from rpc frontendapi.FrontendService.GetChats
     */
    getChats: {
      name: "GetChats",
      I: GetChatsRequest,
      O: GetChatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Starts a chat session.
     *
     * @generated from rpc frontendapi.FrontendService.StartChat
     */
    startChat: {
      name: "StartChat",
      I: StartChatRequest,
      O: StartChatResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets messages in a chat.
     *
     * @generated from rpc frontendapi.FrontendService.GetChatMessages
     */
    getChatMessages: {
      name: "GetChatMessages",
      I: GetChatMessagesRequest,
      O: GetChatMessagesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends a message in a chat.
     *
     * @generated from rpc frontendapi.FrontendService.SendMessage
     */
    sendMessage: {
      name: "SendMessage",
      I: SendMessageRequest,
      O: SendMessageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

