name: Frontend Client CI
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - api/typescript/**
      - .github/workflows/ci-frontend-client.yaml
      - .github/workflows/_check-node.yaml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - client/**
      - api/typescript/**
      - .github/workflows/ci-frontend-client.yaml
      - .github/workflows/_check-node.yaml
      - pnpm-lock.yaml
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: ${{ startsWith(github.ref_name, 'release/') && 'aiceo-prod' || 'aiceo-dev'}}
  GCP_PROJECT_NUMBER: ${{ startsWith(github.ref_name, 'release/') && '1004160178879' || '285404307541'}}

jobs:
  check:
    uses: ./.github/workflows/_check-node.yaml
    with:
      project_dir: client
    secrets: inherit

  deploy:
    needs: check
    runs-on: ubuntu-22.04

    environment: ${{ github.event_name != 'pull_request' && (startsWith(github.ref_name, 'release/') && 'prod' || 'dev') || null }}

    env:
      DOCKER_PUSH: ${{ github.event_name != 'pull_request' && 'yes' || 'no' }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: install dependencies
        run: bun install
        working-directory: client

      - name: build app
        run: bun run build
        working-directory: client
        env:
          PUBLIC_ENV__FIREBASE_APP: ${{ env.GCP_PROJECT_ID }}
          PUBLIC_ENV__GA4_ID: ${{ env.GCP_PROJECT_ID == 'aiceo-dev' && 'G-BKJCB804VR' || 'G-RRBE6EBWR3' }}
          PUBLIC_ENV__DOMAIN: ${{ env.GCP_PROJECT_ID == 'aiceo-dev' && 'alpha.minnano-shacho.curioswitch.org' || 'minnano-shacho.curioswitch.org' }}

      - if: ${{ env.DOCKER_PUSH == 'yes' }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account: firebase-deployer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: deploy app
        if: ${{ env.DOCKER_PUSH == 'yes' }}
        run: bun firebase --project=${{ env.GCP_PROJECT_ID }} deploy
        working-directory: client
