name: Release Build

on:
  push:
    branches:
      - release/**

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  client:
    uses: ./.github/workflows/ci-client.yaml
    secrets: inherit

  server:
    uses: ./.github/workflows/ci-server.yaml
    secrets: inherit
